### ISSUE TITLE
Portfolio item custom fields

### ISSUE THREAD

**Issue by nadek** [RallyCommunity/portfolio-item-copy#5] opened 2017-01-23 18:44 UTC
Custom fields can be very important. I have noticed that when a portfolio item is copied using the portfolio item copy, the values of the custom fields do not carry over.

**Comment by krmorse** [comment] 2019-01-17 19:05
Closing as a dupe of #13.  A fix should be released shortly.

**Closed by krmorse** 2019-01-17 19:05 UTC
