### ISSUE TITLE
Order of child items not the same a source

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [RallyCommunity/portfolio-item-copy#12] opened 2018-10-30 10:18 UTC
When performing a copy af e.g., an initiative with features, the creation order is not the same as the source order - in this regard I'm referring to the ID order (not rank, name or other).

Is there a specific order the new child items are created in? Would it make sense to set this to either ID or rank? Or alternatively as an option in the app settings?

Thank you for the good work.

**Comment by krmorse** [comment] 2019-01-17 19:04
Closing this as a dupe of #4

**Closed by krmorse** 2019-01-17 19:04 UTC
